### ISSUE TITLE
[Windows] NetMon to LibPcap

### ISSUE THREAD

**Issue by MVoz** [joswr1ght/nm2lp#1]
hello, according to the document, https://inguardians.box.com/shared/static/up0ijmv6vrc1nhki6s1h0g4yha6csl0e.pdf

> 5.6 Converting NetMon Captures to Libpcap Format 
> While the NetMon UI has powerful features for analyzing packet captures, few attack tools include the 
> ability to natively read from the NetMon stored capture file format.  In order to leverage tools such as 
> Aircrack-ng, coWPAtty and Cain for wireless analysis, the capture file format needs to be libpcap-
> compatible.  Some tools such as Wireshark support reading and converting NetMon Ethernet captures, 
> but do not correctly interpret NetMon wireless captures. 
> Fortunately, the NetMon API allows developers to write custom applications and interpret data from 
> NetMon stored captures.  Combined with the ability to create a libpcap capture file, it is possible to 
> convert the NetMon file to a libpcap file.  This feature is implemented in nm2lp, released under the GPL 
> v2 license and available at http://www.inguardians.com/tools.
the tool under the windows here http: / / www.inguardians.com / tools

in fact from the https://www.inguardians.com/works tool to be github

> tool: nm2lp (NetMon to LibPcap)
> 
> GitHub link: nm2lp
> 
> while the NetMon ui has powerful features for data packet captures, few attack tools include the ability to natively read from the NetMon stored capture file format. in order to leverage tools such as Aircrack ng, coWPAtty and cain for the financial analysis, the capture file format needs to be libpcap - compatible. some tools such as Wireshark support reading and audio NetMon ethernet captures, but do not correctly interpret NetMon wireless captures. there, the NetMon api allows developers to write custom applications and interpret data from NetMon stored captures. combined with the ability to create a libpcap capture file, it is possible to convert the file to a NetMon libpcap file. nm2lp fun NetMon wireless captures to libpcap format, making them useful in these other tools. you can read more about nm2lp in josh wright's "vista wireless power tools for the analysis tester" paper.
> 
> external tool: microsoft's Wlsample tool for windows vista

but here i found the tools under windows or linux executable files
can you put the binary files?

build from source can't, error

`make`

```
cc -pipe -Wall -I/usr/include/wireshark/wiretap -I/usr/include/wireshark -g3 -ggdb -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/uuid -I/usr/include/harfbuzz -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/atk-1.0 -pthread      -c -o nm2lp.o nm2lp.c
nm2lp.c: В функции «main»:
nm2lp.c:78:19: предупреждение: неявная декларация функции «wtap_phdr»; имелось в виду «wtap_dump»? [-Wimplicit-function-declaration]
   packet_header = wtap_phdr(wtap);
                   ^~~~~~~~~
                   wtap_dump
nm2lp.c:78:17: предупреждение: assignment to «const struct wtap_pkthdr *» from «int» makes pointer from integer without a cast [-Wint-conversion]
   packet_header = wtap_phdr(wtap);
                 ^
nm2lp.c:86:30: ошибка: доступ по указателю на неполный тип «const struct wtap_pkthdr»
    pplinktype = packet_header->pkt_encap;
                              ^~
nm2lp.c:98:17: предупреждение: неявная декларация функции «wtap_buf_ptr»; имелось в виду «wtap_get_buf_ptr»? [-Wimplicit-function-declaration]
   packet_data = wtap_buf_ptr(wtap);
                 ^~~~~~~~~~~~
                 wtap_get_buf_ptr
nm2lp.c:98:15: предупреждение: assignment to «const uint8_t *» {aka «const unsigned char *»} from «int» makes pointer from integer without a cast [-Wint-conversion]
   packet_data = wtap_buf_ptr(wtap);
               ^
make: *** [<встроенное>: nm2lp.o] Ошибка 1
```

**Comment by mfaerevaag** [comment]
I'm having the same problem. Would be great with some feedback on this! 👍

**Comment by joswr1ght** [comment]
I spent some time looking into this. It appears Wireshark has rewritten the API for libwiretap significantly. I have not yet had time to figure out the changes and update `nm2lp`.

If anyone has time to look into it, I'm happy to merge a working PR. I'll keep it on my radar, maybe in the next several weeks I'll be able to free up some time to look into it again.

**Comment by mfaerevaag** [comment]
Ah, no wonder. What version did you write it for? If I can get it running I would like to help :-)

**Comment by joswr1ght** [comment]
It was 4 years ago so Wireshark 1.1'ish. ¯\\_(ツ)_/¯

**Comment by mfaerevaag** [comment]
I got it working with [Wireshark v1.12.4](https://1.na.dl.wireshark.org/src/all-versions/) and libwiretap-dev v1.10.6-1 on Ubuntu 14.04.

Modified [this Dockerfile](https://github.com/sclif13/docker-wireshark/blob/master/Dockerfile) to the following:
```Dockerfile
FROM ubuntu:14.04
MAINTAINER Alexandr Opryshko <sclif13@gmail.com>
ENV DEBIAN_FRONTEND noninteractive

RUN sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list

RUN apt-get update \
&& apt-get --yes build-dep wireshark \
&& apt-get --yes install qt5-default wget libwiretap3 dbus
# fixed url
RUN cd /tmp && wget https://1.na.dl.wireshark.org/src/all-versions/wireshark-1.12.4.tar.bz2 \
&& tar -xjf wireshark-1.12.4.tar.bz2 \
&& cd wireshark-1.12.4 \
&& ./configure && make -j 5 && make install

# install nm2lp deps (notice libwiretab downgrade)
RUN apt-get --yes install libwiretap-dev=1.10.6-1 libpcap-dev libwsutil-dev libgtk2.0-dev libglib2.0-dev

RUN dbus-uuidgen > /etc/machine-id && mkdir /pcap \
&& sed 's/dofile = function() error("dofile " .. hint) end//' /usr/local/share/wireshark/init.lua > /tmp/ddd \
&& mv /tmp/ddd /usr/local/share/wireshark/init.lua

RUN ldconfig
```
